version: '3'

services:
  deepgeek:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:3000/api
      - NEXT_PUBLIC_USE_MOCK_DATA=true
    restart: always
    # 如果需要持久化存储，可以添加volumes
    # volumes:
    #   - ./data:/app/data
